Style/AsciiComments:
  Enabled: false # not to comment in another language than english but to be
                 # able to write tests for non ascii characters

Documentation:
  Enabled: false # this is handled by yard and it is annoying since rubocop does
                 # not notice if a top level class documentation has already
                 # been created (https://github.com/bbatsov/rubocop/issues/691)
