language: ruby
rvm:
- 2.2.2
- jruby-1.7.19
jdk:
- openjdk7
- oraclejdk7
- oraclejdk8
matrix:
  exclude:
    - rvm: 2.2.2
      jdk: oraclejdk7
    - rvm: 2.2.2
      jdk: oraclejdk8
bundler_args: "--without development"
cache: bundler
sudo: false
addons:
  code_climate:
    repo_token: 54a00c87d2ea1ab23262089465bc174c2aa96db287b488afb0061448f9cf1225
deploy:
  provider: rubygems
  api_key:
    secure: aNkBOgCW7ZCsDHp/tSv1C2yxu1FVh9XoClyGNc6IXrvdJ/OouvuLucNXxazD53YnbaRqM5QxyJbl2wMNHrlp7aakjSmmPcHcYGWpZU0AzCaIvzCdoLPxL5GMR0K1CIdyL7KDTDv5ntmEA4iINACYcm20v0EBhY02Tbt1DI/nc9c=
  gem: secret_sharing
  on:
    tags: true
    repo: duse-io/secret_sharing_ruby
