language: ruby
rvm:
- 2.2.2
- jruby-19mode
jdk:
- openjdk6
- openjdk7
- oraclejdk7
- oraclejdk8
matrix:
  exclude:
    - rvm: 2.2.2
      jdk: openjdk7
    - rvm: 2.2.2
      jdk: oraclejdk7
    - rvm: 2.2.2
      jdk: oraclejdk8
env:
- JRUBY_OPTS="-Xcli.debug=true --debug"
bundler_args: "--without development"
cache: bundler
sudo: false
deploy:
  provider: rubygems
  api_key:
    secure: aNkBOgCW7ZCsDHp/tSv1C2yxu1FVh9XoClyGNc6IXrvdJ/OouvuLucNXxazD53YnbaRqM5QxyJbl2wMNHrlp7aakjSmmPcHcYGWpZU0AzCaIvzCdoLPxL5GMR0K1CIdyL7KDTDv5ntmEA4iINACYcm20v0EBhY02Tbt1DI/nc9c=
  gem: secret_sharing
  on:
    tags: true
    repo: duse-io/secret_sharing_ruby
